# Generated by Django 4.2.7 on 2023-11-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_login',
            old_name='mail',
            new_name='e_mail',
        ),
    ]
