# Generated by Django 4.2.7 on 2023-11-30 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('user_name', models.CharField(max_length=100, verbose_name='Nombre_Usuario')),
                ('e_mail', models.CharField(max_length=50, verbose_name='Correo')),
                ('password', models.CharField(max_length=120, verbose_name='Contraseña')),
                ('creation_date', models.DateField(default=datetime.datetime.now, verbose_name='fecha_creacion')),
            ],
            options={
                'verbose_name': 'User_Register',
                'verbose_name_plural': 'Users_Register',
                'db_table': 'User_Register',
                'ordering': ['id'],
            },
        ),
    ]
