# Generated by Django 4.2.6 on 2023-12-03 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(default=datetime.datetime, verbose_name='fecha de registro')),
                ('nom_imagen', models.CharField(max_length=100, verbose_name='Nombre de la imagen')),
                ('id_usuario', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'Registro',
                'ordering': ['id'],
            },
        ),
    ]
