# Generated by Django 4.2.6 on 2024-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_registro_plaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='cultivo',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
