# Generated by Django 4.2.6 on 2024-01-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_alter_registro_cultivo_alter_registro_plaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
