# Generated by Django 4.2.6 on 2024-01-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0009_alter_registro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cultivo',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='registro',
            name='plaga',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
