# Generated by Django 4.2.6 on 2024-01-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0010_alter_registro_cultivo_alter_registro_plaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='respuesta',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
